---
- name: Install Observability using ArgoCD
  redhat.openshift.k8s:
      kubeconfig: config/kube.config
      src: argocd-apps/00_acm-obs.yaml
      state: present

- name: Wait for Objectbucket for Thanos  to be Ready
  ansible.builtin.shell:
      cmd: |
        while ! {{ oc }} get objectbucket obc-open-cluster-management-observability-thanos-bc -n open-cluster-management-observability; do \
          sleep 5
        done
  register: quay_ready
  changed_when: quay_ready

- name: Get Values for thanos object storages endpoint
  ansible.builtin.shell:
      cmd: |
        set -o pipefail
        {{ oc }} get objectbucket {{ thanos_bc }} -n open-cluster-management-observability -o json | jq -r '.spec.endpoint.bucketHost'
  register: s3_endpoint
  changed_when: s3_endpoint.rc

- name: Get Values for thanos object storages endpoint
  ansible.builtin.shell:
      cmd: |
        set -o pipefail
        {{ oc }} get objectbucket {{ thanos_bc }} -n open-cluster-management-observability -o json | jq -r '.spec.endpoint.bucketHost'
  register: s3_endpoint
  changed_when: s3_endpoint.rc

- name: Get Values for thanos object storage name
  ansible.builtin.shell:
      cmd: |
        set -o pipefail
        {{ oc }} get objectbucket {{ thanos_bc }} -n open-cluster-management-observability -o json | jq -r '.spec.endpoint.bucketName'
  register: s3_bucket
  changed_when: s3_bucket.rc

- name: Get Values for thanos object access_key
  ansible.builtin.shell:
      cmd: |
        set -o pipefail
        {{ oc }} get secret thanos-bc -n {{ thanos_ns }} -o json | jq -r '.data.AWS_ACCESS_KEY_ID'
  register: access_key
  changed_when: access_key.rc

- name: Get Values for thanos object secret_key
  ansible.builtin.shell:
      cmd: |
        set -o pipefail
        {{ oc }} get secret thanos-bc -n {{ thanos_ns }} -o json | jq -r '.data.AWS_SECRET_ACCESS_KEY'
  register: secret_key
  changed_when: secret_key.rc

- name: Create TMP folder
  ansible.builtin.file:
      path: files/tmp
      state: directory
      mode: "0775"

- name: Replace template for Thanos Object Storage
  ansible.builtin.template:
      src: template_thanos-object-storage.yaml.j2
      dest: files/tmp/thanos-object-storage.yaml
      mode: preserve

- name: Create Observability additional resources
  redhat.openshift.k8s:
      kubeconfig: config/kube.config
      src: tmp/thanos-object-storage.yaml
      state: present

- name: Wait for Observability Stack to be Ready
  ansible.builtin.shell:
      cmd: |
        while ! {{ oc }} wait MultiClusterObservability observability --for=condition=available --timeout=600s; do \
          sleep 5
        done
  register: quay_ready
  changed_when: quay_ready

- name: Delete Thanos Object Storage Template
  ansible.builtin.file:
      path: files/tmp
      state: absent