---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: acm-obs
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: acm-obs
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
  template:
    metadata:
      name: acm-obs-{{cluster}}
    spec:
      project: acm-obs
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/Everything-is-Code/acm-observability.git
        targetRevision: main
        path: files/resources
      destination:
        server: https://kubernetes.default.svc
