---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: acm
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: acm
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
  template:
    metadata:
      name: acm-{{cluster}}
    spec:
      project: acm
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: git@bitbucket.org:la-segunda/zeroTouchProvisioning.git
        targetRevision: main
        path: components/rhacm-operator/aggregate/
      destination:
        server: https://kubernetes.default.svc
