oc_cli_url: "url_for_cli download"
oc: "./files/binary/oc"
git_repository: ""
git_url: ""
git_private_key: ""
thanos_ns: "open-cluster-management-observability"
thanos_bc: "obc-open-cluster-management-observability-thanos-bc"
access_key: "your_key"
secret_key: "your_secret"
noobaa_secret: "noobaa-aws-cloud-creds-secret"